const Transaction = require('../models/Transaction');
const PDFDocument = require('pdfkit');


const getReports = async (req, res) => {
  try {
    const userId = req.user._id;

    const transactions = await Transaction.find({ user: userId }).sort({ date: -1 });

    let totalIncome = 0;
    let totalExpense = 0;

    transactions.forEach(tx => {
      if (tx.type === 'income')  totalIncome  += tx.amount;
      if (tx.type === 'expense') totalExpense += tx.amount;
    });

    res.render('reports', {
      title:        'Reports — ExpenseIQ',
      user:         req.user,
      summary:      { income: totalIncome, expense: totalExpense },
      transactions,
      categoryData: [],
      monthlyData:  [],
    });

  } catch (error) {
    console.error('Reports Error:', error);
    res.redirect('/dashboard');
  }
};


const exportCSV = async (req, res) => {
  try {
    const transactions = await Transaction.find({ user: req.user._id }).sort({ date: -1 });

    let csv = 'Title,Amount,Type,Category,Date\n';

    transactions.forEach(tx => {
      const date = new Date(tx.date).toLocaleDateString('en-IN');
      csv += `"${tx.title}",${tx.amount},${tx.type},${tx.category},${date}\n`;
    });

    res.setHeader('Content-Type', 'text/csv');
    res.setHeader('Content-Disposition', 'attachment; filename="transactions.csv"');
    res.send(csv);

  } catch (error) {
    console.error('CSV Error:', error);
    res.redirect('/reports');
  }
};


const exportPDF = async (req, res) => {
  try {
    const transactions = await Transaction.find({ user: req.user._id }).sort({ date: -1 });

    let totalIncome = 0;
    let totalExpense = 0;

    transactions.forEach(tx => {
      if (tx.type === 'income')  totalIncome  += tx.amount;
      if (tx.type === 'expense') totalExpense += tx.amount;
    });

    const doc = new PDFDocument({ margin: 50 });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename="report.pdf"');
    doc.pipe(res);

    doc.fontSize(20).font('Helvetica-Bold').text('ExpenseIQ — Financial Report', { align: 'center' });
    doc.fontSize(10).font('Helvetica').fillColor('grey').text(`Date: ${new Date().toLocaleDateString('en-IN')}`, { align: 'center' });
    doc.moveDown();

    doc.fontSize(14).font('Helvetica-Bold').fillColor('black').text('Summary:');
    doc.fontSize(11).font('Helvetica');
    doc.text(`Total Income:   Rs. ${totalIncome.toLocaleString('en-IN')}`);
    doc.text(`Total Expense:  Rs. ${totalExpense.toLocaleString('en-IN')}`);
    doc.text(`Net Balance:    Rs. ${(totalIncome - totalExpense).toLocaleString('en-IN')}`);
    doc.moveDown();

    doc.fontSize(14).font('Helvetica-Bold').text('Transactions:');
    doc.moveDown(0.5);

    transactions.forEach((tx, i) => {
      if (doc.y > 700) doc.addPage();

      const date = new Date(tx.date).toLocaleDateString('en-IN');
      doc.fontSize(10).font('Helvetica').fillColor('black');
      doc.text(`${i + 1}. ${tx.title} | Rs.${tx.amount} | ${tx.type} | ${tx.category} | ${date}`);
    });

    doc.moveDown();
    doc.fontSize(9).fillColor('grey').text('Generated by ExpenseIQ', { align: 'center' });

    doc.end();

  } catch (error) {
    console.error('PDF Error:', error);
    res.redirect('/reports');
  }
};


module.exports = { getReports, exportCSV, exportPDF };
